# Generated by Django 5.2.15 on 2026-06-15 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)')], max_length=20, verbose_name='plataforma')),
                ('account_name', models.CharField(max_length=255, verbose_name='nome da conta')),
                ('account_id', models.CharField(max_length=255, verbose_name='ID da conta')),
                ('_access_token', models.TextField(db_column='access_token', verbose_name='token de acesso (criptografado)')),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token', verbose_name='token de refresh (criptografado)')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='token expira em')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_accounts', to=settings.AUTH_USER_MODEL, verbose_name='conectado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='accounts.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'conta social',
                'verbose_name_plural': 'contas sociais',
                'ordering': ['platform', 'account_name'],
                'unique_together': {('organization', 'platform', 'account_id')},
            },
        ),
    ]
