# Generated by Django 5.2.15 on 2026-06-15 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('login', 'Login'), ('logout', 'Logout'), ('publish', 'Publicação'), ('connect', 'Conexão OAuth'), ('other', 'Outro')], max_length=20, verbose_name='ação')),
                ('resource_type', models.CharField(blank=True, max_length=100, verbose_name='tipo de recurso')),
                ('resource_id', models.CharField(blank=True, max_length=255, verbose_name='ID do recurso')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.organization', verbose_name='organização')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
