# Generated by Django 5.2.15 on 2026-06-15 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='título')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('media', models.JSONField(blank=True, default=list, verbose_name='mídias')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('publishing', 'Publicando'), ('published', 'Publicado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(verbose_name='agendado para')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('publishing', 'Publicando'), ('published', 'Publicado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('external_post_id', models.CharField(blank=True, max_length=255, verbose_name='ID externo')),
                ('api_response', models.JSONField(blank=True, default=dict, verbose_name='resposta da API')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.post', verbose_name='post')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='integrations.socialaccount', verbose_name='conta social')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
